Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -119,3 +119,70 @@ jobs:
       - name: Run tests
         working-directory: pl/packages/plentymarkets/plugin-test-suite
         run: vendor/bin/phpunit vendor/plentymarkets/plugin-io
+      - name: Set job status
+        if: always()
+        run: |
+          echo "${{ job.status }}" > "${RUNNER_TEMP}/${STATUS_FILE}"
+
+          # add "optional" if test is not required
+          if ! ${{ matrix.php.required }}; then
+            echo " optional" >> "${RUNNER_TEMP}/${STATUS_FILE}"
+          fi
+
+      - name: Upload matrix status artifact
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: job-status
+          path: ${{ runner.temp }}/${{ env.STATUS_FILE }}
+          retention-days: 1
+  collect-results:
+    # checks results of all previous jobs for failures
+    needs: [unit-tests]
+    name: Test overall status
+    runs-on: ["self-hosted", "stable", "medium", "spot"]
+    if: always()
+    steps:
+      - uses: plentymarkets/github-runner-cleanup@main
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          path: ${{ runner.temp }}
+
+      - name: Summarize jobs status
+        shell: bash
+        run: |
+          FILES=$(find "${{ runner.temp }}/job-status" -type f -name "test.*.status")
+
+          OVERALL_STATUS="success"
+
+          RED='\033[0;31m'
+          NC='\033[0m'
+
+          while IFS="" read -r FILE; do
+
+            FILENAME=$(basename "${FILE}")
+            STATUS=$(cat "$FILE" | xargs)
+
+            printf "${FILENAME}: "
+
+            if [[ "$STATUS" != "success"* ]]; then
+
+              printf "${RED}${STATUS}${NC}\n"
+
+              if [[ "$STATUS" != *"optional"* ]]; then
+                OVERALL_STATUS=$STATUS
+              fi
+            else
+              echo "${STATUS}"
+            fi
+
+          done <<< "$FILES"
+
+          if [[ "$OVERALL_STATUS" != "success" ]]; then
+            printf "\n${RED}At least one required job failed!${NC}\n"
+            exit 1
+          else
+            printf "\nAll required jobs were successful.\n"
+          fi
